In [1]:
import pandas as pd
import numpy as np
from bokeh.io import output_file, show, save
from bokeh.layouts import widgetbox, gridplot
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.models.widgets import TableColumn, DataTable
from bokeh.plotting import figure

In [2]:
df_bokeh = pd.read_csv('bokeh_chart.csv', index_col = 0)
df_bokeh

                   name    year        bmi         0         1
0            Jason Adam  2018.0  27.384868  0.567163  0.432837
1          Austin Adams  2017.0  28.885135  0.348052  0.651948
2          Austin Adams  2018.0  28.885135  0.238642  0.761358
3           Matt Albers  2006.0  29.681929  0.559188  0.440812
4           Matt Albers  2007.0  29.681929  0.782302  0.217698
5           Matt Albers  2008.0  29.681929  0.637852  0.362148
6           Matt Albers  2009.0  29.681929  0.922627  0.077373
7           Matt Albers  2010.0  29.681929  0.888755  0.111245
8           Matt Albers  2011.0  29.681929  0.823404  0.176596
9           Matt Albers  2012.0  29.681929  0.801778  0.198222
10          Matt Albers  2013.0  29.681929  0.835083  0.164917
11          Matt Albers  2014.0  29.681929  0.233789  0.766211
12          Matt Albers  2015.0  29.681929  0.523649  0.476351
13          Matt Albers  2016.0  29.681929  0.542022  0.457978
14          Matt Albers  2017.0  29.681929  0.887294  0.112706
15          Matt Albers  2018.0  29.681929  0.194822  0.805178
16      Sandy Alcantara  2017.0  20.690789  0.295718  0.704282
17      Sandy Alcantara  2018.0  20.690789  0.351418  0.648582
18     Victor Alcantara  2017.0  24.391892  0.296352  0.703648
19     Victor Alcantara  2018.0  24.391892  0.466153  0.533847
20      Scott Alexander  2015.0  24.391892  0.295108  0.704892
21      Scott Alexander  2016.0  24.391892  0.481119  0.518881
22      Scott Alexander  2017.0  24.391892  0.950188  0.049812
23      Scott Alexander  2018.0  24.391892  0.897473  0.102527
24           Cody Allen  2012.0  27.703134  0.662957  0.337043
25           Cody Allen  2013.0  27.703134  0.983453  0.016547
26           Cody Allen  2014.0  27.703134  0.984064  0.015936
27           Cody Allen  2015.0  27.703134  0.994041  0.005959
28           Cody Allen  2016.0  27.703134  0.961146  0.038854
29           Cody Allen  2017.0  27.703134  0.976229  0.023771
...                 ...     ...        ...       ...       ...
3100      Mike Zagurski  2007.0  32.546296  0.624700  0.375300
3101      Mike Zagurski  2010.0  32.546296  0.299939  0.700061
3102      Mike Zagurski  2011.0  32.546296  0.235806  0.764194
3103      Mike Zagurski  2012.0  32.546296  0.695642  0.304358
3104      Mike Zagurski  2013.0  32.546296  0.207556  0.792444
3105      Mike Zagurski  2018.0  32.546296  0.122862  0.877138
3106      Rob Zastryzny  2016.0  25.620444  0.473327  0.526673
3107      Rob Zastryzny  2017.0  25.620444  0.259624  0.740376
3108      Rob Zastryzny  2018.0  25.620444  0.278961  0.721039
3109       Brad Ziegler  2008.0  26.776316  0.884563  0.115437
3110       Brad Ziegler  2009.0  26.776316  0.974031  0.025969
3111       Brad Ziegler  2010.0  26.776316  0.910754  0.089246
3112       Brad Ziegler  2011.0  26.776316  0.962254  0.037746
3113       Brad Ziegler  2012.0  26.776316  0.964855  0.035145
3114       Brad Ziegler  2013.0  26.776316  0.962838  0.037162
3115       Brad Ziegler  2014.0  26.776316  0.890049  0.109951
3116       Brad Ziegler  2015.0  26.776316  0.915436  0.084564
3117       Brad Ziegler  2016.0  26.776316  0.958797  0.041203
3118       Brad Ziegler  2017.0  26.776316  0.794617  0.205383
3119       Brad Ziegler  2018.0  26.776316  0.724008  0.275992
3120  Jordan Zimmermann  2009.0  28.885135  0.923938  0.076062
3121  Jordan Zimmermann  2010.0  28.885135  0.413684  0.586316
3122  Jordan Zimmermann  2011.0  28.885135  0.987208  0.012792
3123  Jordan Zimmermann  2012.0  28.885135  0.988528  0.011472
3124  Jordan Zimmermann  2013.0  28.885135  0.991447  0.008553
3125  Jordan Zimmermann  2014.0  28.885135  0.998121  0.001879
3126  Jordan Zimmermann  2015.0  28.885135  0.979527  0.020473
3127  Jordan Zimmermann  2016.0  28.885135  0.779468  0.220532
3128  Jordan Zimmermann  2017.0  28.885135  0.815616  0.184384
3129  Jordan Zimmermann  2018.0  28.885135  0.728012  0.271988

[3130 rows x 5 columns]

In [3]:
df_years = df_bokeh.groupby('name').count().iloc[:, :1].reset_index()

In [4]:
df_chart = pd.merge(df_bokeh, df_years, on = 'name', how = 'outer').rename(columns = {'year_y':'yoc'})

In [5]:
df_chart = df_chart[df_chart['year_x'] == 2018]

In [18]:
df_chart = df_chart[~df_chart.name.isin(['Scooter Gennett','Chris Davis','Leonys Martin', 'Pablo Sandoval'])]
df_chart['1'] = df_chart['1'].round(2)

In [19]:
df_chart.head()

                name  year_x        bmi         0     1  yoc
0         Jason Adam  2018.0  27.384868  0.567163  0.43    1
2       Austin Adams  2018.0  28.885135  0.238642  0.76    2
15       Matt Albers  2018.0  29.681929  0.194822  0.81   13
17   Sandy Alcantara  2018.0  20.690789  0.351418  0.65    2
19  Victor Alcantara  2018.0  24.391892  0.466153  0.53    2

In [26]:
df_chart[df_chart.name.str.contains('Gennett')]

Empty DataFrame
Columns: [name, year_x, bmi, 0, 1, yoc]
Index: []

In [29]:
output_file('docs/index.html', title = 'Last-year index dashboard')
source = ColumnDataSource(df_chart)
columns = [TableColumn(field = 'name', title = 'Player'),
           TableColumn(field = '1', title = 'Last Year Index')]
data_table = DataTable(source = source, columns = columns)




hover = HoverTool(tooltips = (
[
    ('Name', '@name'),
    ('BMI', '@bmi'),
    ('Years since debut', '@yoc'),]))

tools = [hover, 'box_zoom', 'tap']
p = figure(
    title = 'BMI vs Career Longevity for Active Pitchers',
    plot_width = 800,
    plot_height = 600,
    tools = tools
)
p.yaxis.axis_label = 'Years since MLB debut'
p.xaxis.axis_label = 'BMI'


           
p.scatter(x = 'bmi', y = 'yoc', source = source, size = 8)
save(p)

grid = gridplot([[p, widgetbox(data_table)]])
save(grid)

'/home/ethanarsht/fat_baseball/docs/index.html'

In [28]:
output_file('/home/ethanarsht/Downloads/check.html', title = 'Last-year index dashboard')
source = ColumnDataSource(df_chart)
columns = [TableColumn(field = 'name', title = 'Player'),
           TableColumn(field = '1', title = 'Last Year Index')]
data_table = DataTable(source = source, columns = columns)




hover = HoverTool(tooltips = (
[
    ('Name', '@name'),
    ('BMI', '@bmi'),
    ('Years since debut', '@yoc')]))

tools = [hover, 'box_zoom', 'tap']
p = figure(
    title = 'BMI vs Career Longevity for Active Pitchers',
    plot_width = 800,
    plot_height = 600,
    tools = tools
)
p.yaxis.axis_label = 'Years since MLB debut'
p.xaxis.axis_label = 'BMI'


           
p.scatter(x = 'bmi', y = 'yoc', source = source, size = 8)
save(p)

grid = gridplot([[p, widgetbox(data_table)]])
save(grid)

'/home/ethanarsht/Downloads/check.html'